[project]
name = "unicorp_turtles_42"
description = "PyWeek 42 game - Borrowed Time"
readme = "README.rst"
version = "0.0.4"
authors = [
  { name="Xyolidge" },
  { name="Ratnarchiste" },
  { name="gkrnours" },
]

requires-python = ">=3.13"
dependencies = [
  "pyglet",
]

[project.urls]
Homepage = "https://pyweek.org/e/uniturtles/"

[project.scripts]
turtle = "unicorp_turtles_42.main:run"

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"*" = ["gfx/*.png", "*.txt"]

[tool.isort]
multi_line_output = 3
